apiVersion: v1
kind: Service
metadata: 
  labels:
    name: {{ .Values.global.name }}-frontend
  name: {{ .Values.global.name }}-frontend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: {{ .Values.global.name }}-frontend
