apiVersion: v1
kind: Service
metadata: 
  labels:
    name: {{ .Values.global.name }}-frontend
  name: {{ .Values.global.name }}-frontend
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 4200
  selector:
    app: {{ .Values.global.name }}-frontend
